language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - addon
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
  - mkdir -p /home/travis/sdcard/
  - mksdcard -l baldphonesdcard 128M /home/travis/sdcard/sdcard.img
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -camera-back none -camera-front none -no-boot-anim -sdcard /home/travis/sdcard/sdcard.img -no-snapshot-save &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell pm disable com.android.launcher
  - ./gradlew installbaldUpdatesDebug
  - adb shell settings put secure enabled_notification_listeners %nlisteners:com.bald.uriah.baldphone/com.bald.uriah.baldphone.services.NotificationListenerService
  - adb shell ime enable com.bald.uriah.baldphone/.keyboard.BaldInputMethodService
  - adb shell ime set com.bald.uriah.baldphone/.keyboard.BaldInputMethodService

  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedbaldUpdatesDebugAndroidTest
  - pwd
  - cd /home/travis
  - pwd
  - git config --global user.email "uriah.shm@outlook.com"
  - git config --global user.name "UriahShaulMandel"
  - git clone https://github.com/UriahShaulMandel/BaldPhoneScreenshots.git
  - pwd
  - cd BaldPhoneScreenshots
  - pwd
  - mkdir -p /home/travis/BaldPhoneScreenshots/screenshots
  - pwd
  - adb pull /sdcard/Pictures/screenshots /home/travis/BaldPhoneScreenshots/screenshots
  - pwd
  - git add --all :/
  - pwd
  - git commit -am "committest1"
  - pwd
  - git push
before_install:
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
dd:
  secure: kp7Bw9boFlD2Zq2W4pZi2FNscbdjG0jskAtESep/vuldrRz/3H6xFXtuWpZg6YXlAVn5mx6jMVQl8j+hw+NLgQ7BktSmhrNgoXIgQ2ZGjsv2pu3VrLGz57chD7hgeNGLaDr9SSFu3AElI6hCJuXjgkyDSATRG4F+IQ/3NT1twg7oArzYVfH6atGdtTljeuaEet2+6fIVoIcuQ0WgkorH7Kem/TGNiuSqzA6wNL2FQSL2Ff+hloFhbmHdeYh6glxhZltygOKRfxsFbDn7WBkCi/xh+F7FWZve5CTEmeGiw49z3Ydjh8IUkWmw+1LMqM0zQo2P88a1rIZlViXR9y8wI98YYvhMQPKmgQ5DSKl1WBVjBl0AxE/ou419iCQnIiB2KCUZn6UwPEvxBD7qSo6QInZVdMr6K+bKRYpsCi1BjARoJ7qqHVNajQOmL0qwXVuLnvKArNxN0DVFsUG1VqVVfw04EXXkC19Kl8mVvsBTxYdzdAsvuZZiQ4vse4K9L+kOWexVDPNhSNPSKhbG0sNFh09buIz1Pe7r4hTHEoYzlilRkG5W1YtiU9cp93a4MrC5wZ3WQ3z3IpBARmA9ehVQZyRzxDxpt7PJiuXqT8Ojdq6RY39b3CrOcwJkmPiu1vSOUC+Jj7+7pWykIQMbbubN0LspbZgNnff2YAse8FS8XuQ=

