language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra
    - addon
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew

  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell pm disable com.android.launcher
  - ./gradlew installDebug
  - adb shell settings put secure enabled_notification_listeners %nlisteners:com.bald.uriah.baldphone/com.bald.uriah.baldphone.services.NotificationListenerService
  - adb shell ime enable com.bald.uriah.baldphone/.keyboard.BaldInputMethodService
  - adb shell ime set com.bald.uriah.baldphone/.keyboard.BaldInputMethodService
  - adb shell
  - $su
  - mount -o rw,remount rootfs /
  - chmod 777 /mnt/sdcard
  - exit
  - adb shell screencap -p /sdcard/screen.png
  - adb shell am broadcast -a android.intent.action.MEDIA_MOUNTED -d file:///sdcard
  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedAndroidTest
before_install:
  - echo yes | android update sdk --all --filter build-tools-28.0.3 --no-ui --force
